from __future__ import unicode_literals

INTENT = "intent"
INTENTS = "intents"
ENTITIES = "entities"
UTTERANCES = "utterances"
USE_SYNONYMS = "use_synonyms"
SYNONYMS = "synonyms"
DATA = "data"
VALUE = "value"
TEXT = "text"
ENTITY = "entity"
SLOT_NAME = "slot_name"
TRUE_POSITIVE = "true_positive"
FALSE_POSITIVE = "false_positive"
FALSE_NEGATIVE = "false_negative"
INTENT_UTTERANCES = "intent_utterances"
PARSING_ERRORS = "parsing_errors"
METRICS = "metrics"
